spring.application.name=springboot
server.port=8081

logging.level.com.webservice=DEBUG
logging.file.name=logs/app.log
logging.file.max-size=5MB

spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
